### PR TITLE
Fix some bugs

### PR DESCRIPTION
**Pull request by AndreyDeg**
Hi! Thanks for BMPDecoder. I use it and find some bugs

### CODE REVIEW

**Comment by EricHaung** [comment]
Thank you so much ! 
it's almost my first published code and make me so surprise to get reply.
Sorry bring you problems, i'll try harder next time.

**Comment by AndreyDeg** [comment]
You are welcome!
I testing BMPDecoder and compare result with System.Drawing.Bitmap(in C#). I see small different in Decode16BitImage. I try fix it later

**Comment by EricHaung** [comment]
Thank you for your notification.

Cause I have to working at morning, I'll test it tonight (UTC+8).

**Comment by EricHaung** [comment]
I found this:

http://entropymine.com/jason/bmpsuite/bmpsuite/html/bmpsuite.html

which recording lot of BMP format.

I guess you are testing some kind format my code not supporting.

I'll try to include them in future.

**Pull request merged**
